### ISSUE TITLE
[Question] Why the images are not cached but downloaded every time?

### ISSUE THREAD

**Issue by saragluna** [Azure-Samples/acme-fitness-store#16]
When trying to load the static images, such as `static/images/yogamat_square.jpg`, seems like the images are not cached but downloaded every time. Is this expected?

**Comment by maly7** [comment]
Thanks for the question, @saragluna. This is expected because the application doesn't include any additional caching. [d145f5a](https://github.com/Azure-Samples/acme-fitness-store-config/commit/d145f5aa2a5e856d0402a08d1725cec602bb89b0) updates the configuration for catalog service to include `cache-control` headers for static content.

**Comment by saragluna** [comment]
Thanks @maly7, closing this issue now.
